apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-automation
spec:
  selector:
    matchLabels:
      app: dev-automation
  replicas: 2
  template:
    metadata:
      labels:
        app: dev-automation
    spec:
      containers:
        - name: dev-automation
          image: masud1122/dev-automation
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
