apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-automation
spec:
  selector:
    matchLabels:
      app: dev-automation
  replicas: 2
  template:
    metadata:
      labels:
        app: dev-automation
    spec:
      containers:
        - name: dev-automation
          image: masud1122/dev-automation
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---

apiVersion: v1
kind: Service
metadata:
  name: dev-automation-service
spec:
  selector:
    app: dev-automation
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
